@startuml
left to right direction
skinparam packageStyle rectangle
actor sistema
actor cliente
rectangle MarQueTin {
  sistema -- (contactar) 
  (contactar) -- cliente
  (contactar) .> (forma de contacto) : include
}
@enduml